add structural and behavior test files from Artemis
ls1intum/artemis-java-test-sandbox pull request #62
Opened 2020-11-11 15:44 UTC by krusche

This PR adds the files of the default Java programming exercise template.
Currently we copy lots of files into many different repositories that does not need to be change at all.
Putting those into a library such as artemis-java-test-sandbox makes much more sense, therefore I added this PR.
I will create a corresponding PR in Artemis which updates the Java programming exercise template based on these changes.

- [ ] Deploy the snapshot version to Maven so that we can test it in an actual Artemis exercise
- [ ] Release a new official version of artemis-java-test-sandbox (e.g. 1.3.4) and use this in the Artemis template

2020-11-11 22:13 UTC, kloessst requested changes
Tested this locally with the corresponding Artemis PR. Java template works as expected but Kotlin has problems with class scanning.

2020-11-11 22:13 UTC, kloessst commented on src/main/java/de/tum/in/test/api/structural/testutils/ClassNameScanner.java
> +        if(fileName.contains(".java")) {
Won't work for Kotlin `.kv` files

2020-11-11 22:13 UTC, kloessst commented on src/main/java/de/tum/in/test/api/structural/testutils/ClassNameScanner.java
> +            String packageName = node.getPath().substring(0, node.getPath().indexOf(".java"));
Won't work for Kotlin .kv files

2020-11-16 14:43 UTC, kloessst commented on src/main/java/de/tum/in/test/api/structural/testutils/ClassNameScanner.java
> +		if (distance > 2)
Is the comment false or is the distance literal incorrect? Souldn't it be "with a distance below **two** as typo"

2020-11-17 16:45 UTC, MaisiKoleni requested changes

2020-11-17 16:45 UTC, MaisiKoleni commented on src/main/java/de/tum/in/test/api/structural/AttributeTestProvider.java
> +			fail("The LocalAttributeTest test can only run if the structural oracle (test.json) is present. If you do not provide it, delete LocalAttributeTest.java!");
This needs to be adjusted now as well (same for the other classes).

2020-11-17 16:45 UTC, MaisiKoleni commented on src/main/java/de/tum/in/test/api/structural/AttributeTestProvider.java
> +			fail("No tests for attributes available in the structural oracle (test.json). Either provide attributes information or delete AttributeTest.java!");
This should still be correct?

2020-11-17 17:05 UTC, MaisiKoleni approved these changes
Looks good to me.

2020-11-17 17:07 UTC, kloessst approved these changes
Skimmed through the code looks fine!

2020-11-17 17:26 UTC, merged