Simple and canonical name support for Structure Test Oracle files
ls1intum/artemis-java-test-sandbox pull request #67
Opened 2020-11-19 20:09 UTC by niclasschuemann

At the moment, ClassTest only allows simple class names for implemented interfaces and superclasses in the structure oracle test file. This is problematic because it is not validated that the actually correct interface or superclass is implemented.
If one exercise contains two interfaces with the same name but in different packages respectively, the ClassTest cannot determine which one of these is the correct one.
Therefore AJTS should be able to handle simple as well as canonical class names in the structure test oracle file correctly. 
Simple names can still be used if the location of an interface or a superclass is up to the student and canonical names will be used if the location of the interface or superclass is already given.

2020-11-20 16:47 UTC, MaisiKoleni requested changes
This is a good idea 👍 

Could you format the code (so that the code style check passes)? You can use Maven `spotless:apply` for that. And because of the second commit: the project here is using tabs, so it was correct before in that regard.

Regarding the changes: 
I think being able to compare the full canonical name of types is a good improvement in general. Could we use this approach consistently for classes in the structural tests? This would apply to e.g. attributes, parameter types and return types. Could you therefore create a protected method in `StructuralTestProvider` that is used for all such comparisons? This would also reduce the duplication of the logic.

2020-11-21 22:53 UTC, niclasschuemann commented
I have implemented your suggested changes for almost all type occurrences except for attribute types since this is implemented a little bit differently. I will look into that tomorrow and formally request a re-review 👍

2020-11-22 08:42 UTC, MaisiKoleni commented
> I have implemented your suggested changes for almost all type occurrences except for attribute types since this is implemented a little bit differently. I will look into that tomorrow and formally request a re-review 👍

We could also look into that together, I would have two more suggestions. You can contact me on the LS1-Slack.

2020-12-08 19:06 UTC, MaisiKoleni commented on src/main/java/de/tum/in/test/api/structural/StructuralTestProvider.java
>  		 */
For a followup: use the new type checking here as well.

2020-12-08 19:08 UTC, MaisiKoleni approved these changes
Looks good to me, parameters can be adjusted later as well. We could also think about a better way to generate canonical names, but this should be good enough for almost all cases.

2020-12-08 19:13 UTC, merged